apiVersion: v1
kind: ConfigMap
metadata:
  name: bench-env
data:
  SIZES: "1024,2048,4096,8192,16384,32768,65536,131072,262144,524288,1048576,2097152,4194304,8388608,16777216"
#  SIZES: "1024,2048,4096,8192,16384,32768,65536,131072,262144,524288,1048576,2097152,4194304,8388608"
  REPS: "20"