apiVersion: v1
kind: Pod
metadata:
  name: file-bench-disk
  labels:
    role: file-bench
    storage: disk
spec:
  volumes:
    - name: data
      emptyDir: {}
  containers:
    - name: reader
      image: file-reader:local
      imagePullPolicy: Never
      volumeMounts:
        - mountPath: /data
          name: data
      env:
        - name: STORAGE_MEDIUM
          value: "disk"
      envFrom:
        - configMapRef:
            name: bench-env
      resources:
        requests:
          memory: "128Mi"
        limits:
          memory: "512Mi"
    - name: writer
      image: file-writer:local
      imagePullPolicy: Never
      volumeMounts:
        - mountPath: /data
          name: data
      env:
        - name: STORAGE_MEDIUM
          value: "disk"
      envFrom:
        - configMapRef:
            name: bench-env
      resources:
        requests:
          memory: "128Mi"
        limits:
          memory: "512Mi"
