apiVersion: v1
kind: Pod
metadata:
  name: file-bench
  labels:
    role: file-bench
spec:
  volumes:
    - name: data
      emptyDir: { }
  containers:
    - name: reader
      image: file-reader:local
      volumeMounts:
        - mountPath: /data
          name: data
      envFrom:
        - configMapRef:
            name: bench-env

    - name: writer
      image: file-writer:local
      volumeMounts:
        - mountPath: /data
          name: data
      envFrom:
        - configMapRef:
            name: bench-env