#apiVersion: v1
#kind: Pod
#metadata:
#  name: file-bench
#  labels:
#    role: file-bench
#spec:
#  volumes:
#    - name: data
#      emptyDir:
#        medium: Memory
#  containers:
#    - name: reader
#      image: file-reader:local
#      imagePullPolicy: Never
#      volumeMounts:
#        - mountPath: /data
#          name: data
#      envFrom:
#        - configMapRef:
#            name: bench-env
#
#    - name: writer
#      image: file-writer:local
#      imagePullPolicy: Never
#      volumeMounts:
#        - mountPath: /data
#          name: data
#      envFrom:
#        - configMapRef:
#            name: bench-env